name: Run Jest Tests and upload Artifacts

on:
  push:
    branches: [ "main" ]

jobs:
  artifacts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          npm install
      - name: Build project assets
        run: npm run build

      - name: Upload static site content
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: ./test-results
